export const krishnaNames = [
    "Achala - The firm one",
    "Achyuta - The infallible one",
    "Adbhutah - The wonderful one",
    "Adideva - The Lord of lords",
    "Aditya - Son of Aditi",
    "Ajanma - The unborn one",
    "Ajaya - One who cannot be defeated",
    "Akshara - The indestructible one",
    "Amrit - Heavenly nectar that provides immortality",
    "Anand-sagar - Sea of joy",
    "Ananta - One who is endless",
    "Anantajeet - The ever-victorious one",
    "Ananya - One who has no superior",
    "Aniruddha - One who cannot be obstructed",
    "Aparajit - One who cannot be defeated",
    "Avyukta - One who is very clearly visible",
    "Balagopala - The child form of Krishna",
    "Balkrishna - The child form of Krishna",
    "Chaturbhuja - One with four arms",
    "Danavendra - Giver of boons",
    "Dayalu - Repository of compassion",
    "Dayanidhi - The compassionate Lord",
    "Devadidev - The God of gods",
    "Devakinandana - Son of Devaki",
    "Devesha - The Lord of lords",
    "Dharmadhyaksha - Lord of Dharma",
    "Dravin - The one without enemies",
    "Dwarkapati - Lord of Dwarka",
    "Gopal - Maintainer of cows",
    "Gopalpriya - Lover of the cowherds",
    "Govinda - One who gives pleasure to the cows; Knower of the activities of the senses",
    "Gyaneshwar - Lord of knowledge",
    "Hari - Absorber of all sorrows and pains; Lord of nature",
    "Hiranyagarbha - The all-powerful creator",
    "Hrishikesha - Lord of the senses",
    "Jagadguru - Preceptor of the entire universe",
    "Jagadisha - Protector of the universe",
    "Jagannath - Lord of the universe",
    "Janardana - One who afflicts felons; One who grants the prayers of devotees",
    "Jayantah - Ever-victorious one",
    "Jyotiraditya - Brightness of the sun",
    "Kamalnath - Lord of Goddess Lakshmi",
    "Kamalnayan - One with lotus-shaped eyes",
    "Kamsantak - Slayer of Kamsa",
    "Kanjalochana - Lotus-eyed one",
    "Keshava - Slayer of demon Keshi; One with long, beautiful hair",
    "Krishna - All-attractive one; Dark complexioned one",
    "Lakshikantam - Lord of Goddess Lakshmi",
    "Lokadhyaksha - Lord of all worlds",
    "Madan - Lord of love",
    "Madhava - Husband of Laxmi",
    "Madhusudana - Slayer of demon Madhu",
    "Mahendra - Lord of Indra",
    "Manmohan - The mind-pleasing one",
    "Manohar - One who pleases the mind",
    "Mayur - Lord with a peacock-feathered crest",
    "Mohan - All-attractive one",
    "Murali - Flute-playing Lord",
    "Murlidhar - Holder of flute",
    "Murlimanohar - The one who pleases the mind with flute-playing",
    "Nandagopala - Son of Nanda",
    "Nandakumara - Son of Nanda",
    "Narayana - The refuge of all",
    "Navaneetha-chor - Thief of butter",
    "Niranjana - Unblemished one",
    "Nirguna - One without attributes",
    "Padmahasta - One whose hands are like lotus",
    "Padmanabha - One who has a lotus-shaped navel",
    "Parabrahmana - The supreme absolute truth",
    "Paramatma - The Supreme Soul",
    "Param-purush - The Highest Person",
    "Parthasarathi - Charioteer of Partha (Arjuna)",
    "Prajapati - Lord of all beings",
    "Punyah - The pure one",
    "Purushuttama - The best of all men; The supreme person",
    "Ravilochana - One who has the sun as His eyes",
    "Sahasraakash - The thousand-eyed one",
    "Sahasrajit - One who vanquishes thousands",
    "Sakshi - One who witnesses everything",
    "Sanatana - The eternal one",
    "Sarvajana - The omniscient one",
    "Sarvapalaka - Maintainer of all",
    "Sarveshwar - The Lord of all",
    "Satyavachana - Speaker of truth",
    "Satyavrata - One who is dedicated to truth",
    "Shantah - The peaceful one",
    "Shrestha - The highest one",
    "Shrikanta - The beautiful one",
    "Shyam - Dark-complexioned one",
    "Shyamsundar - Dark and Beautiful",
    "Sumedha - Intelligent one",
    "Suresham - Lord of the demigods",
    "Swargapati - The Lord of heavenly planets",
    "Trivikrama - Conqueror of the three worlds",
    "Upendra - Brother of Indra",
    "Vaikunthanath - The Lord of Vaikuntha",
    "Varshneya - Descendant of Vrishni",
    "Vasudeva - Son of Vasudeva",
    "Vishnu - The all-pervading Lord",
    "Vishwadakshinah - The most skillful one",
    "Vishwakarma - Creator of the universe",
    "Vishwamurte - The form of the entire universe",
    "Vishwarupa - One who is the same as the universe",
    "Vishwatma - Soul of the universe",
    "Vrishaparva - Lord of Dharma",
    "Yadava - Descendant of Yadu",
    "Yadavendra - King of the Yadav clan",
    "Yoginampati - Lord of the Yogis"
  ] as const;
  